### ISSUE TITLE
'Productprocesslink' has no attribute 'yesterday', old database

### ISSUE THREAD

**Issue by balarsen** [spacepy/dbprocessing#20]
Another database change in the chain. 

### Minimal example to reproduce issue:

```
ectsoc@spacesci-1: /home/ectsoc/hope_tmp /$ ~/dbUtils/reprocessByDate.py -m ~/PROCESSING_DB/hope.sqlite -s 20160101 -e 20160101
ectsoc@spacesci-1: /home/ectsoc/hope_tmp /$  bash -lc "cd /home/ectsoc/tmp;nice -n 6 /home/ectsoc/dbUtils/ProcessQueue.py -p -n8 -m /home/ectsoc/PROCESSING_DB/hope.sqlite --log-level=info"
[2020-08-26T13:22:23] Building commands for 44 items in the queue
Command Build Progress: ...0%Traceback (most recent call last):
  File "/home/ectsoc/dbUtils/ProcessQueue.py", line 171, in <module>
    run_procs=options.o)
  File "/home/ectsoc/miniconda2/lib/python2.7/site-packages/dbprocessing/dbprocessing.py", line 385, in buildChildren
    files, input_product_id = self._getRequiredProducts(child_process, file_id[0], utc_file_date)
  File "/home/ectsoc/miniconda2/lib/python2.7/site-packages/dbprocessing/dbprocessing.py", line 271, in _getRequiredProducts
    input_product_id = self.dbu.getInputProductID(process_id, True)  # this is a list of tuples (id, optional, yesterday, tommorow)
  File "/home/ectsoc/miniconda2/lib/python2.7/site-packages/dbprocessing/DButils.py", line 1713, in getInputProductID
    self.Productprocesslink.yesterday, self.Productprocesslink.tomorrow)\
AttributeError: type object 'Productprocesslink' has no attribute 'yesterday'
```

### Version of dbprocessing
362a0b72b868d5ad6019784acd6052d07b8d2a35

This issue should be closed when: Van ALlen Probes processing can continue

**Comment by jtniehof** [comment]
Thanks. Those were supposed to gracefully handle older db, but clearly didn't. Will add a test to make sure this works.

**Comment by balarsen** [comment]
Might be easiest to modify old databases to work rather than modify code for special cases. What are `yesterday` and `tomorrow` supposed to hold? Those appear to be 
```
        :param yesterday: How many extra days back do you need
        :type yesterday: int
        :param tomorrow: How many extra days forward do you need
        :type tomorrow: int
```
so a database update would be pretty easy.

**Comment by jtniehof** [comment]
I think they can be null or 0. You don't want 1. See #7.

Still probably best to keep the code compatible, but if it's turning into a hole I'll loop back in with an update.

**Comment by jtniehof** [comment]
@balarsen , this should be fixed in #21, but do you want to leave the issue open until you know you can continue with processing? I have on my plate the more general issue of running a HOPE day and whack-a-moleing any errors.

**Comment by balarsen** [comment]
I pulled and ran this, seems to be working. I will stop and let you whack a mole. 

```
$  ~/dbUtils/reprocessByDate.py -m ~/PROCESSING_DB/hope.sqlite -s 20160101 -e 20160101

2016-01-01 00:00:00 2016-01-01 00:00:00
Added 1 files to be reprocessed
$  bash -lc "cd /home/ectsoc/tmp;nice -n 6 /home/ectsoc/dbUtils/ProcessQueue.py -p -n8 -m /home/ectsoc/PROCESSING_DB/hope.sqlite --log-level=info"
```

I note that the 
```
Command Build Progress: 37:44 ...84%
```
is a lot slower than it used to be.

**Comment by balarsen** [comment]
@jtniehof things are a bit out of whack with the magephems, the V1.0.0 files are gone and not all the v3.0.0 are ingested yet into hope. But that is not too bad,

**Comment by jtniehof** [comment]
Slower than it was before this fix, or slower than it was before you moved onto the new dbp period?

**Comment by jtniehof** [comment]
Holy _smoke_ that's slow. Might not be because of these changes, but I'll take a quick poke. Will follow up in ECT progressing discussion.
