### ISSUE TITLE
PR checklist calls for CHANGELOG update, yet there is no changelog

### ISSUE THREAD

**Issue by balarsen** [spacepy/dbprocessing#42]
My suggested enhancement is that there should be a changelog. 

### Proposed enhancement

Minor, is there a preferred format for these?

### Version of dbprocessing

20afffc47c2d8d30018af953372c59fa0d82d87a

### Closure condition
This issue should be closed when we are happy with a changelog format.

**Comment by jtniehof** [comment]
Duplicate of #28

**Comment by balarsen** [comment]
> 
> 
> Duplicate of #28

Yep, thanks I did actually look but it didn't say CHANGELOG in the title ;-)
