### ISSUE TITLE
Clean up tags in repo

### ISSUE THREAD

**Issue by jtniehof** [spacepy/dbprocessing#48]
I'm showing 19 tags in my repo. I haven't pushed any to github. I'm reluctant to just delete at this point in case we need that info, but it might confuse things once we start tagging releases here. Here's the list:

```
2.0.1           tagged all 2.0.1 and uploaded to cvs
2.0.2           updated and cvs commit of 2.0.2
2.0.3           version 2.0.3 cvs version bump
DBStrings0.1    DBStrings v. 0.1: functional, but about to overhaul to split regex/nonregex
DBStrings0.2    DBStrings 0.2: total overhaul/streamline
DBStrings0.3    DBStrings 0.3: finally implements everything required for ProcessQueue
OP1             dbprocessing.py: typo fix in the versing checking code of revision
OP2             Merge branch 'master' into production
OP3             Merge branch 'master' into production
OP4             Merge branch 'master' into production
OP5             Merge branch 'master' into production
OP6             Merge branch 'master' into production
OP7             Merge branch 'master' into production
cmmt87510       CVS commit: Made unit tests work again; added a way to run them all together.
cmmt87599       Sync with git: remove files moved to Old_code; add SQL for creating DB
cmmt88272       Convert code command line specs to python format strings
comm_ver_1      bugfixes
hope_v1.0.0     many changes to get working for HOPE
ver_1.0.0       DBUtils.py: added support for 'RUN' output_timebase, runs each time
```
The DBStrings ones are my fault and can definitely go. The "cmmtxxxx" ones are probably from when we were using both CVS and git and can probably also go. 

### Closure condition
This issue should be closed when appropriate tags have been chosen and pushed to github and the rest deleted in other repos. (It might also be time to delete some of the old shared repos.)

**Comment by balarsen** [comment]
None of those have any value to me

**Comment by jtniehof** [comment]
Alright, I've deleted all tags on my local copy and also on our local shared copy. I think we agreed that the python3 branch was useless, correct? All my other branches have been merged, so I'll clean them up.

Any reason not to also axe the bitbucket repo?

**Comment by jtniehof** [comment]
Since we have Python 3 support now, I've deleted the python3 branch. I'm going to close this issue now; @balarsen , up to you to delete the bitbucket repo.
